# Generated by Django 6.0.4 on 2026-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GareRoutiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gare_routiere',
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee_est', models.TimeField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('places_totales', models.IntegerField()),
                ('places_disponibles', models.IntegerField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trajet',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('capacite', models.IntegerField()),
                ('type_vehicule', models.CharField(default='taxi-brousse', max_length=50)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_maintenance', 'Maintenance'), ('inactif', 'Inactif')], default='actif', max_length=20)),
            ],
            options={
                'db_table': 'vehicule',
            },
        ),
    ]
