# Generated by Django 6.0.4 on 2026-04-21 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trajets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='chauffeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.chauffeur'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='gare_arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivee', to='trajets.gareroutiere'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='gare_depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='trajets.gareroutiere'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='chauffeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.chauffeur'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajets.vehicule'),
        ),
    ]
