# Generated by Django 6.0.4 on 2026-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embarquement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_scan', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('invalide', 'Invalide')], default='valide', max_length=20)),
            ],
            options={
                'db_table': 'embarquement',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_billet', models.CharField(max_length=20, unique=True)),
                ('nb_places', models.IntegerField(default=1)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('guichet', 'Guichet')], default='web', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('embarquee', 'Embarquée')], default='en_attente', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
