# Generated by Django 6.0.4 on 2026-04-21 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('trajets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarquement',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.agent'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agent'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='passager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.passager'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajets.trajet'),
        ),
        migrations.AddField(
            model_name='embarquement',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
    ]
