# Generated by Django 6.0.4 on 2026-05-12 05:46

import apps.reservations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agent'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='code_billet',
            field=models.CharField(default=apps.reservations.models.generer_code, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nb_places',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
